ads/urls.py
from django.urls import path, reverse_lazy

from . import views

app_name = 'ads'

urlpatterns = [
    path('', views.AdListView.as_view(), name='all'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/create',
         views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),
    path('ad/<int:pk>/update',
         views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),
    path('ad/<int:pk>/delete',
         views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),
    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),
    path('ad/<int:pk>/comment',
         views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete',
         views.CommentDeleteView.as_view(success_url=reverse_lazy('ads')), name='ad_comment_delete'),
    path('ad/<int:pk>/favorite',
         views.AddFavoriteView.as_view(), name='ad_favorite'),
    path('ad/<int:pk>/unfavorite',
         views.DeleteFavoriteView.as_view(), name='ad_unfavorite'),
]

ads_mag/urls.py
import os
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.views.static import serve

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROOT = os.path.join(BASE_DIR, 'site')

urlpatterns = [
                  path('', include('ads.urls')),
                  path('admin/', admin.site.urls),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('oauth/', include('social_django.urls', namespace='social')),
                  path('profile/', include('core.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('accounts/', include('django_registration.backends.one_step.urls')),
                  path('chat/', include('chat.urls')),
                  path('favicon.ico', serve, {
                      'path': 'favicon.ico',
                      'document_root': os.path.join(BASE_DIR, 'core/static'),
                  }),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


social_login = 'registration/login_social.html'
urlpatterns.insert(0,
                   path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                   )

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('<int:user_id>', views.ProfileView.as_view(), name='profile'),
    path('<int:user_id>/edit', views.ProfileUpdateView.as_view(), name='profile_update'),
    path('profile_picture/<int:pk>', views.stream_file, name='profile_picture'),
]

djangoProject/urls.py
import os
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.views.static import serve

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROOT = os.path.join(BASE_DIR, 'site')

urlpatterns = [
                  path('', include('ads.urls')),  # Change to ads.urls
                  path('admin/', admin.site.urls),  # Keep
                  path('accounts/', include('django.contrib.auth.urls')),  # Keep
                  url(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep
                  # path('', TemplateView.as_view(template_name='home/main.html')),
                  path('profile/', include('home.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('accounts/', include('django_registration.backends.one_step.urls')),
                  path('favicon.ico', serve, {
                      'path': 'favicon.ico',
                      'document_root': os.path.join(BASE_DIR, 'home/static'),
                  }
                       ),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings

    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

core/models.py
from django.db import models
from django.contrib.auth.models import User
from phone_field import PhoneField


class UserProfile(models.Model):
    home_address = models.CharField(max_length=120, null=True, default='', blank=True)
    phone_number = PhoneField(blank=False, help_text='Contact phone number')
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    picture = models.BinaryField(null=True, editable=True)
    content_type = models.CharField(max_length=256, null=True, help_text='The MIMEType of the file')
    birthdate = models.DateField(null=True, verbose_name='Date of birth', blank=True)

core/forms.py
from django import forms
from django.core.files.uploadedfile import InMemoryUploadedFile
from ads.humanize import naturalsize
from core.models import UserProfile


class ProfileForm(forms.ModelForm):
    max_upload_limit = 2 * 256 * 256
    max_upload_limit_text = naturalsize(max_upload_limit)
    picture = forms.FileField(required=False, label='File to Upload <= ' + max_upload_limit_text)
    upload_field_name = 'picture'

    class Meta:
        model = UserProfile
        labels = {
            'home_address': 'Your home address',
            'phone_number': 'Phone number',
            'birthdate': 'Date of birth',
        }
        fields = ['home_address', 'phone_number', 'birthdate', 'picture']
        widgets = {'birthdate': forms.SelectDateWidget(years=range(1930, 2003))}

    def clean(self):
        """
        Validates the size of the picture
        :return: None
        """
        cleaned_data = super().clean()
        pic = cleaned_data.get('picture')
        if pic is None:
            return
        if len(pic) > self.max_upload_limit:
            self.add_error('picture', "File must be < " + self.max_upload_limit_text + " bytes")

    def save(self, commit=True):
        instance = super(ProfileForm, self).save(commit=False)

        # We only need to adjust picture if it is a freshly uploaded file
        f = instance.picture  # Make a copy
        if isinstance(f, InMemoryUploadedFile):  # Extract data from the form to the model
            bytearr = f.read()
            instance.content_type = f.content_type
            instance.picture = bytearr  # Overwrite with the actual image data

        if commit:
            instance.save()

        return instance

core/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseForbidden, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import View
from django.contrib.auth.models import User
from .models import UserProfile
from .forms import ProfileForm
from django.core.exceptions import ObjectDoesNotExist


class ProfileView(LoginRequiredMixin, View):
    template_name = 'profile.html'

    def get(self, request, user_id):
        try:
            user = User.objects.get(id=user_id)
            profile, created = UserProfile.objects.get_or_create(user=user)
            context = {
                'user': user,
                'profile': profile
            }
            return render(request, self.template_name, context)
        except ObjectDoesNotExist:
            return HttpResponse('User does not exist')


class ProfileUpdateView(LoginRequiredMixin, View):
    template_name = 'profile_form.html'

    def get(self, request, user_id):
        if request.user.id == user_id:
            profile, created = UserProfile.objects.get_or_create(user=user_id)
            form = ProfileForm(instance=profile)
            context = {'form': form}
            return render(request, self.template_name, context)
        else:
            return HttpResponse('<p>You have no permission to edit this page</p>'
                                f'<a href={reverse_lazy("ads:all")}>Go back</a>')

    def post(self, request, user_id):
        if request.user.id != user_id:
            return HttpResponse('<p>You have no permission to edit this page</p>'
                                f'<a href={reverse_lazy("ads:all")}>Go back</a>')
        profile, created = UserProfile.objects.get_or_create(user=self.request.user)
        form = ProfileForm(request.POST, request.FILES or None, instance=profile)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        profile = form.save(commit=False)
        profile.save()

        return redirect(reverse_lazy('core:profile', args=[user_id]))


def stream_file(request, pk):
    profile = get_object_or_404(UserProfile, id=pk)
    response = HttpResponse()
    response['Content-Type'] = profile.content_type
    response['Content-Length'] = len(profile.picture)
    response.write(profile.picture)
    return response

core/templates/base_bootstrap.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>

    {% load static %}

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Staatliches&display=swap" rel="stylesheet">
    {% block head %} {% endblock %}

</head>
<body>
    {% block navbar %} {% endblock %}

<div class="container site-container">
    {% block welcome %} {% endblock %}
    {% block messages %}
        {% if messages %}
            {% for msg in messages %}
                <div class="alert alert-{{ msg.level_tag }}" role="alert">
                    {{ msg.message }}
                </div>
            {% endfor %}
        {% endif %}
    {% endblock %}
    {% block content %}
    {% endblock %}
</div>
{% block footer %} {% endblock %}
</body>
</html>

core/templates/base_menu.html
{% extends "base_bootstrap.html" %}
{% load static %}
{% block navbar %}
    {% load app_tags %}

    <nav class="navbar navbar-expand-lg navbar-light bg-dark fixed-top">
    <div class="row px-5">
      <a class="navbar-brand text-white" href="{% url 'ads:all' %}" id="brand">{{ settings.APP_NAME }}</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
          aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      {% url 'ads' as ads %}
        <li class="nav-item {% if request.get_full_path == ads %} active {% endif %}">
                    <a href="{% url 'ads:all' %}" class="nav-link text-white">All ads</a></li>
    {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{% url 'ads:ad_create' %}">Create Ad</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdownMenuLink"
                           role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <img style="width: 25px;" src="{% if request.user.userprofile.picture %}
                                                    {% url 'core:profile_picture' request.user.userprofile.id %}
                                        {% else %} {% static 'no-image.jpg' %}{% endif %}" alt="placeholder"/>
                            <b class="caret"></b>
                        </a>
                        <div class="dropdown-menu bg-dark" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item text-white" href="{% url 'core:profile' request.user.id %}">Profile</a>
                            <a class="dropdown-item text-white" href="{% url 'logout' %}?next={% url 'ads:all' %}">Logout</a>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a href="{% url 'login' %}?next={% url 'ads:all' %}" class="nav-link text-white">Login</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'django_registration_register' %}?next={% url 'ads:all' %}"
                           class="nav-link text-white">Register</a>
                    </li>
                {% endif %}
    </ul>
  </div>
    </div>
</nav>
{% endblock %}

core/templates/profile.html
{% extends "base_menu.html" %}
{% load static %}
{% load crispy_forms_filters %}

{% block content %}

<div id="overlay" class="overlay text-center" onclick="document.getElementById('overlay').style.display = 'none';">
            <img id="img-overlay" src="{% if profile.picture %} {{ profile.picture.url }}
                                        {% else %} {% static 'no-image.jpg' %}{% endif %}" alt="placeholder">
        </div>
    <div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-6">
            <div class="well well-sm">
                <div class="row">

                    <div class="col-sm-6 col-md-4">
                        <img class="img-overlay" style="width: 150px"
                             src="{% if profile.picture %} {% url 'core:profile_picture' profile.id %}
                                        {% else %} {% static 'no-image.jpg' %}{% endif %}" alt="placeholder">
                    </div>
                    <div class="col-sm-6 col-md-8">
                        <h4>{{ user.username }}</h4>
                        <small><cite title="{{ profile.home_address }}">{{ profile.home_address }} <i class="glyphicon glyphicon-map-marker">
                        </i></cite></small>
                        <p>
                            <i class="glyphicon glyphicon-envelope"></i>{{ user.email }}
                            <br />
                            <i class="glyphicon glyphicon-gift"></i>
                            {{ profile.phone_number }}
                        <br>
                            {% if profile.birthdate %}
                                {{ profile.birthdate }}
                            {% endif %}
                            </p>
                    </div>

            </div>
            {% if request.user == user %}
            <div class="btn btn-sm btn-success mt-2"><a href="{% url 'core:profile_update' user.id %}"
                                                       style="color: white" class="nav-link"> Edit your profile </a></div>
            {% endif %}
                </div>
        </div>
    </div>
</div>
{% endblock %}

core/templates/profile_form.html
{% extends "base_menu.html" %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="col-4">
<p>
  <form action="" method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-success">
    <input type="submit" value="Cancel" class="btn btn-outline-success" onclick="window.location.href='{% url 'ads:all' %}';return false;">
  </form>
</p>
        </div>
<script>
$("#upload_form").submit(function() {
  console.log('Checking file size');
  if (window.File && window.FileReader && window.FileList && window.Blob) {
      var file = $('#id_{{ form.upload_field_name }}')[0].files[0];
      if (file && file.size > {{ form.max_upload_limit }} ) {
          alert("File " + file.name + " of type " + file.type + " must be < {{ form.max_upload_limit_text }}");
      return false;
    }
  }
});
</script>
{% endblock %}