ads/urls.py
from django.urls import path, reverse_lazy

from . import views

app_name = 'ads'

urlpatterns = [
    path('', views.AdListView.as_view(), name='all'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/create',
         views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),
    path('ad/<int:pk>/update',
         views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),
    path('ad/<int:pk>/delete',
         views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),
    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),
    path('ad/<int:pk>/comment',
         views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete',
         views.CommentDeleteView.as_view(success_url=reverse_lazy('ads')), name='ad_comment_delete'),
    path('ad/<int:pk>/favorite',
         views.AddFavoriteView.as_view(), name='ad_favorite'),
    path('ad/<int:pk>/unfavorite',
         views.DeleteFavoriteView.as_view(), name='ad_unfavorite'),
]

ads_mag/urls.py
import os
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.views.static import serve

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROOT = os.path.join(BASE_DIR, 'site')

urlpatterns = [
                  path('', include('ads.urls')),
                  path('admin/', admin.site.urls),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('oauth/', include('social_django.urls', namespace='social')),
                  path('profile/', include('core.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('accounts/', include('django_registration.backends.one_step.urls')),
                  path('chat/', include('chat.urls')),
                  path('favicon.ico', serve, {
                      'path': 'favicon.ico',
                      'document_root': os.path.join(BASE_DIR, 'core/static'),
                  }),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


social_login = 'registration/login_social.html'
urlpatterns.insert(0,
                   path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                   )

chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'

urlpatterns = [
    path('<str:room_name>/', views.room, name='room'),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('<int:user_id>', views.ProfileView.as_view(), name='profile'),
    path('<int:user_id>/edit', views.ProfileUpdateView.as_view(), name='profile_update'),
    path('profile_picture/<int:pk>', views.stream_file, name='profile_picture'),
]

djangoProject/urls.py
import os
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.views.static import serve

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROOT = os.path.join(BASE_DIR, 'site')

urlpatterns = [
                  path('', include('ads.urls')),  # Change to ads.urls
                  path('admin/', admin.site.urls),  # Keep
                  path('accounts/', include('django.contrib.auth.urls')),  # Keep
                  url(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep
                  # path('', TemplateView.as_view(template_name='home/main.html')),
                  path('profile/', include('home.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('accounts/', include('django_registration.backends.one_step.urls')),
                  path('favicon.ico', serve, {
                      'path': 'favicon.ico',
                      'document_root': os.path.join(BASE_DIR, 'home/static'),
                  }
                       ),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings

    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

ads/models.py
from django.conf import settings
from django.core.validators import MinLengthValidator, MaxLengthValidator, MinValueValidator, MaxValueValidator
from django.db import models


class Ad(models.Model):
    title = models.CharField(
        max_length=200,
        validators=[MinLengthValidator(2, "Title must be greater than 2 characters")]
    )
    price = models.DecimalField(max_digits=7, decimal_places=2, null=True,
                                validators=[MinValueValidator(0)])
    text = models.CharField(max_length=250,
                            validators=[MaxLengthValidator(250, 'Description must be less than 250 characters')])
    fulldesc = models.TextField(default="")
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    picture = models.BinaryField(null=True, editable=True)
    content_type = models.CharField(max_length=256, null=True, help_text='The MIMEType of the file')
    comments = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                      through='Comment', related_name='comments_owned')
    favorites = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                       through='Fav', related_name='favorite_ads')

    def __str__(self):
        return self.title

    def get_likes(self):
        return Fav.objects.filter(ad=self).count()


class Comment(models.Model):
    text = models.TextField(
        validators=[MinLengthValidator(3, "Comment must be greater than 3 characters")]
    )

    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        if len(self.text) < 15:
            return self.text
        return f'{self.text[:11]}...'


class Fav(models.Model):
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['ad', 'user'], name='unique fav')
        ]

    def __str__(self):
        return '%s likes %s' % (self.user.username, self.ad.title[:10])

ads/forms.py
from django import forms
from django.core.files.uploadedfile import InMemoryUploadedFile
from ads.humanize import naturalsize
from ads.models import Ad, Comment


class CreateForm(forms.ModelForm):
    max_upload_limit = 2 * 1024 * 1024
    max_upload_limit_text = naturalsize(max_upload_limit)
    picture = forms.FileField(required=False, label='File to Upload <= ' + max_upload_limit_text)
    upload_field_name = 'picture'

    class Meta:
        model = Ad
        labels = {
            'text': 'Short description',
            'fulldesc': 'Full description',
        }
        fields = ['title', 'text', 'fulldesc', 'price', 'picture']

    def clean(self):
        """
        Validates the size of the picture
        :return: None
        """
        cleaned_data = super().clean()
        pic = cleaned_data.get('picture')
        if pic is None:
            return
        if len(pic) > self.max_upload_limit:
            self.add_error('picture', "File must be < " + self.max_upload_limit_text + " bytes")

    def save(self, commit=True):
        """
        Converts uploaded File object to a picture
        :param commit: determines whether the record is committed to database
        :return: object instance
        """
        instance = super(CreateForm, self).save(commit=False)

        # We only need to adjust picture if it is a freshly uploaded file
        f = instance.picture  # Make a copy
        if isinstance(f, InMemoryUploadedFile):  # Extract data from the form to the model
            bytearr = f.read()
            instance.content_type = f.content_type
            instance.picture = bytearr  # Overwrite with the actual image data

        if commit:
            instance.save()

        return instance


class CommentForm(forms.Form):
    comment = forms.CharField(required=False, max_length=500, min_length=3, strip=True)

    class Meta:
        model = Comment
        labels = {
            'text': 'Leave a comment',
        }
        fields = ['text']

ads/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.humanize.templatetags.humanize import naturaltime
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from .forms import CreateForm, CommentForm
from .models import Ad, Comment, Fav
from .owner import OwnerListView, OwnerDetailView, OwnerDeleteView


class AdListView(OwnerListView):
    model = Ad
    template_name = 'ads/ad_list.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        search = self.request.GET.get("search", False)
        if search:
            query = Q(title__icontains=search)
            query.add(Q(text__icontains=search), Q.OR)
            self.ads = queryset.filter(query).select_related().order_by('-updated_at')[:10]
        else:
            self.ads = queryset

    def get(self, request):
        self.get_queryset()
        for obj in self.ads:
            obj.natural_updated = naturaltime(obj.updated_at)

        favorites = list()
        if request.user.is_authenticated:
            rows = request.user.favorite_ads.values('id')
            favorites = [row['id'] for row in rows]

        ctx = {'ad_list': self.ads, 'favorites': favorites}

        return render(request, self.template_name, ctx)


class AdDetailView(OwnerDetailView):
    model = Ad
    template_name = 'ads/ad_detail.html'

    def get(self, request, pk):
        try:
            ad = get_object_or_404(Ad, id=pk)
            comments = Comment.objects.filter(ad=ad).order_by('updated_at')
            comment_form = CommentForm()
            context = {
                'ad': ad,
                'comments': comments,
                'comment_form': comment_form,
                'comments_count': len(comments)
            }
            return render(request, self.template_name, context)
        except Ad.DoesNotExist:
            return HttpResponse(f'<p>There is no such item</p><a href="{reverse_lazy("ads:all")}">Go back</a>')


class AdCreateView(LoginRequiredMixin, View):
    template_name = 'ads/ad_form.html'
    success_url = reverse_lazy('ads:ad_detail')

    def get(self, request):
        form = CreateForm()
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request):
        form = CreateForm(request.POST, request.FILES or None)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        # Add owner to the model before saving
        ad = form.save(commit=False)
        ad.owner = self.request.user
        ad.save()
        return redirect(self.success_url)


class AdUpdateView(LoginRequiredMixin, View):
    template_name = 'ads/ad_form.html'
    success_url = reverse_lazy('ads:ad_detail')

    def get(self, request, pk):
        ad = get_object_or_404(Ad, id=pk, owner=self.request.user)
        form = CreateForm(instance=ad)
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        ad = get_object_or_404(Ad, id=pk, owner=self.request.user)
        form = CreateForm(request.POST, request.FILES or None, instance=ad)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        ad = form.save(commit=False)
        ad.save()

        return redirect(self.success_url)


class AdDeleteView(OwnerDeleteView):
    model = Ad


def stream_file(request, pk):
    ad = get_object_or_404(Ad, id=pk)
    response = HttpResponse()
    response['Content-Type'] = ad.content_type
    response['Content-Length'] = len(ad.picture)
    response.write(ad.picture)
    return response


class CommentCreateView(LoginRequiredMixin, View):
    def post(self, request, pk):
        ad = get_object_or_404(Ad, id=pk)
        comment = Comment(text=request.POST['comment'], owner=request.user, ad=ad)
        comment.save()
        return redirect(reverse('ads:ad_detail', args=[pk]))


class CommentDeleteView(OwnerDeleteView):
    model = Comment
    template_name = "ads/comment_delete.html"

    def get_success_url(self):
        ad = self.object.ad
        return reverse('ads:ad_detail', args=[ad.id])


@method_decorator(csrf_exempt, name='dispatch')
class AddFavoriteView(LoginRequiredMixin, View):

    def post(self, request, pk):
        print("Add PK", pk)
        ad = get_object_or_404(Ad, id=pk)
        fav, created = Fav.objects.get_or_create(user=request.user, ad=ad)
        fav.save()  # In case of duplicate key
        return HttpResponse()


@method_decorator(csrf_exempt, name='dispatch')
class DeleteFavoriteView(LoginRequiredMixin, View):

    def post(self, request, pk):
        print("Delete PK", pk)
        ad = get_object_or_404(Ad, id=pk)
        Fav.objects.filter(user=request.user, ad=ad).delete()
        return HttpResponse()

ads/templates/ads/ad_confirm_delete.html
{% extends "base_menu.html" %}
{% block content %}
    <h1>Delete Ad</h1>

    <p>Are you sure you want to delete the ad: {{ ad }}?</p>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes, delete.">
    </form>
{% endblock %}

ads/templates/ads/ad_detail.html
{% extends "base_menu.html" %}
{% load static %}
{% load crispy_forms_filters %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->
{% block head %}
{% endblock %}
{% block content %}
    {% if ad.content_type %}
        <div id="overlay" class="overlay text-center"
             onclick="document.getElementById('overlay').style.display = 'none';">
            <img id="img-overlay" src="{% url 'ads:ad_picture' ad.id %}" alt="{{ ad.title }}">
        </div>
    {% endif %}
    <span style="float: right;">
(Updated {{ ad.updated_at|naturaltime }})
        {% if ad.owner == user %}
            <a href="{% url 'ads:ad_update' ad.id %}">Edit</a> |
            <a href="{% url 'ads:ad_delete' ad.id %}">Delete</a>
        {% endif %}
</span>
    <h1>{{ ad.title }}</h1>
    <div class="row">
        <div class="col-4">
            {% if ad.content_type %}
                <img class="rounded w-100 border border-dark ad-image" src="{% url 'ads:ad_picture' ad.id %}"
                     alt="{{ ad.title }}" onclick="document.getElementById('overlay').style.display = 'block';">
            {% else %}
                <img class="rounded w-100 border border-dark ad-image" src="{% static 'no-image.jpg' %}"
                     alt="{{ ad.title }}">
            {% endif %}
        </div>
        <div class="col-8">
            <a href="{% url 'chat:room' ad.owner %}" class="btn btn-sm btn-success">Contact seller</a>
            <h4>{{ ad.text }}</h4>
            <h5>{{ ad.price }}</h5>
            <p>{{ ad.fulldesc }}</p>
        </div>
    </div>

    <div class="page-header mt-5">
        <h4>Comments <small class="float-right text-muted">{{ comments_count }} comment{{ comments_count|pluralize }}</small></h4>
    </div>
    <div class="row rounded bg-light my-3">

        <div class="col">
            <div class="comments-list">
                {% for comment in comments %}
                    <div class="media">
                        <a class="float-left mr-3 mt-2" href="{% url 'core:profile' comment.owner.id %}">
                            <img src="{% if comment.owner.userprofile.picture %}
                                {% url 'core:profile_picture' comment.owner.userprofile.id %}
                                        {% else %} {% static 'no-image.jpg' %}{% endif %}"
                                 alt="userpic" style="width: 50px">
                        </a>
                        <div class="media-body">
                            {% if user == comment.owner %}
                                <a href="{% url 'ads:ad_comment_delete' comment.id %}"
                                   class="float-right small">Delete</a>
                            {% endif %}
                            <h5 class="media-heading user_name">{{ comment.owner.get_username }} wrote:</h5>
                            <p>{{ comment.text }}</p>
                            <p><small class="text-muted">({{ comment.updated_at|naturaltime }})</small></p>
                        </div>


                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    {% if user.is_authenticated %}
        <p class="mb-3">
            {% load crispy_forms_tags %}
        <form method="post" action="{% url 'ads:ad_comment_create' ad.id %}">
            {% csrf_token %}
            {{ comment_form|crispy }}
            <input type="submit" class="btn btn-success" value="Submit">
            <input type="submit" class="btn btn-outline-success" value="Cancel"
                   onclick="window.location.href='{% url 'ads:all' %}';return false;">
        </form>
        </p>
    {% endif %}
{% endblock %}

ads/templates/ads/ad_form.html
{% extends "base_menu.html" %}
{% load crispy_forms_tags %}
{% block content %}
<p>
  <form action="" method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'ads:all' %}';return false;">
  </form>
</p>
<!-- https://stackoverflow.com/questions/2472422/django-file-upload-size-limit -->
<script>
$("#upload_form").submit(function() {
  console.log('Checking file size');
  if (window.File && window.FileReader && window.FileList && window.Blob) {
      var file = $('#id_{{ form.upload_field_name }}')[0].files[0];
      if (file && file.size > {{ form.max_upload_limit }} ) {
          alert("File " + file.name + " of type " + file.type + " must be < {{ form.max_upload_limit_text }}");
      return false;
    }
  }
});
</script>
{% endblock %}

ads/templates/ads/ad_list.html
{% extends "base_menu.html" %}
{% load humanize %}
{% load static %}
{% block content %}
    <p>
    <div class="mb-3">
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search.." name="search"
                    {% if search %} value="{{ search }}" {% endif %}
                   aria-label="Search">
            <button class="btn btn-outline-success btn my-2 my-sm-0" type="submit">Search</button>
            <a href="{% url 'ads:all' %}" class="ml-2"><i class="fa fa-undo"></i></a>
        </form>
    </div>
    <div class="row justify-content-around">
        {% if ad_list %}

            {% for ad in ad_list %}

                <div class="card mb-3 mx-auto" style="width: 45%;">
                    <div class="row no-gutters">
                        <div class="col-md-4">
                            {% if ad.content_type %}
                                <img class="card-img" src="{% url 'ads:ad_picture' ad.id %}" alt="{{ ad.title }}">
                            {% else %}
                                <img class="card-img" src="{% static 'no-image.jpg' %}" alt="{{ ad.title }}">
                            {% endif %}
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <h5 class="card-title">{{ ad.title }}</h5>
                                <p class="card-text">{{ ad.text }}</p>
                                <p class="card-text font-weight-bold">{{ ad.price }}</p>
                                <a href="{% url 'ads:ad_detail'  ad.id %}" class="btn btn-sm btn-success">See detail</a>
                                {% if user.is_authenticated %}
                                    <!-- Two hrefs with two stacked icons each - one showing and one hidden -->
                                    <a href="#" class="text-decoration-none" onclick=
                                            "favPost('{% url 'ads:ad_unfavorite' ad.id %}', {{ ad.id }});return false;"
                                            {% if ad.id not in favorites %} style="display: none;" {% endif %}
                                       id="favorite_heart_{{ ad.id }}">
                        <span class="fa-stack" style="vertical-align: middle;">
                        <i class="fa fa-heart fa-stack-1x" style="color: #337ab7;"></i>
                        <i class="fa fa-heart-o fa-stack-1x"></i>
                        </span>{{ ad.get_likes }}
                                    </a>
                                    <!-- the second href -->
                                    <a href="#" class="text-decoration-none" onclick=
                                            "favPost('{% url 'ads:ad_favorite' ad.id %}', {{ ad.id }});return false;"
                                            {% if ad.id in favorites %} style="display: none;" {% endif %}
                                       id="unfavorite_heart_{{ ad.id }}">
                        <span class="fa-stack" style="vertical-align: middle;">
                        <i class="fa fa-heart fa-stack-1x" style="display: none; color: #337ab7;"></i>
                        <i class="fa fa-heart-o fa-stack-1x"></i>
                        </span>{{ ad.get_likes }}
                                    </a>
                                {% endif %}
                                <p class="card-text"><small class="text-muted">Last
                                    updated {{ ad.updated_at|naturaltime }}</small></p>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <p>There are no ads in the database.</p>
        {% endif %}
    </div>


    <script>
        function favPost(url, ad_id) {
            console.log('Requesting JSON');
            $.post(url, {}, function () {
                console.log(url, 'finished');
                $("#unfavorite_heart_" + ad_id).toggle();
                $("#favorite_heart_" + ad_id).toggle();
            }).fail(function (xhr) {
                alert('Url failed with ' + xhr.status + ' ' + url);
            });
        }
    </script>
{% endblock %}

ads/templates/ads/comment_delete.html
{% extends "base_menu.html" %}
{% block content %}
    <h1>Delete Comment</h1>

    <p>Are you sure you want to delete</p>
    <p>{{ comment.text }}?</p>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Yes, delete.">
        <a href="{% url 'ads:ad_detail' comment.ad.id %}" class="btn btn-secondary">Cancel</a>
    </form>
{% endblock %}